### ISSUE TITLE
Add social buttons

### ISSUE THREAD

**Issue by antonvasin** [techtim/tvl.gatsby#6]
Add icons with links to social accounts to the header and contact

**Comment by antonvasin** [comment]
@techtim кнопки добавил, нужны линки. FB и Vimeo, как в макете. Если хочешь что-то еще или другое (я бы не стал фб указывать), то напиши тут

**Comment by techtim** [comment]
почему без фб?
https://www.facebook.com/timvisuals/
https://vimeo.com/timtvl

**Comment by techtim** [comment]
https://www.youtube.com/channel/UCUMPgeNiY0WnSZCiyxHOquQ
